"""
teacher.py — "The Teacher" / output-formatting layer of the Hourglass.

Takes only VERIFIED claims (never anything still pending QC) and renders two
real, distinct output tiers as specified in the original brief:
  - PRO tier: exact specs, ohm/voltage ranges, procedure steps, citations.
  - DIY / Roadside tier: plain-English, numbered, no-jargon steps for
    someone stressed on the side of the road with a multimeter and a phone.

Both tiers are generated from the *same* verified data — this is the
"expand and teach" step: once data clears the neck of the Hourglass, it is
formatted outward for every audience without re-deriving the facts.
"""

from typing import List, Dict, Any


def _fmt_citations(citations: List[str]) -> str:
    return "; ".join(citations)


def format_pro_report(domain: str, verified: List[Dict[str, Any]]) -> str:
    lines = [f"# {domain} — Professional Diagnostic Reference", ""]
    lines.append(
        "Generated by the RideWire Hourglass pipeline. Every entry below cleared "
        "Devil's QC (independent-source corroboration). Confidence reflects the "
        "number of independent domains that corroborate the claim, not just link count."
    )
    lines.append("")

    for c in sorted(verified, key=lambda x: x["fact_id"]):
        lines.append(f"## {c['fact_id']} ({c['category']}) — Confidence: {c['confidence']}")
        lines.append(c["statement"])
        if c.get("numeric_range"):
            lines.append(f"- Spec: `{c['numeric_range']}`")
        lines.append(f"- Corroborated by {c['independent_domain_count']} independent sources.")
        lines.append(f"- Citations: {_fmt_citations(c['citations'])}")
        lines.append("")

    return "\n".join(lines)


def format_diy_report(domain: str, verified: List[Dict[str, Any]]) -> str:
    lines = [f"# {domain} — Roadside / DIY Quick Guide", ""]
    lines.append(
        "If you're stuck on the side of the road: read this top to bottom, in order. "
        "You'll need a basic multimeter."
    )
    lines.append("")

    # Order matters for a roadside flow: battery first, then symptoms, then tests.
    priority_order = [
        "F8_BATTERY_FIRST_RULE",
        "F9_STATIC_VOLTAGE_SPEC",
        "F1_RUNNING_VOLTAGE",
        "F2_LOW_VOLTAGE_STATOR",
        "F3_HIGH_VOLTAGE_REGULATOR",
        "F10_GROUND_MIMICS_FAILURE",
        "F4_STATOR_AC_OUTPUT_TEST",
        "F5_STATOR_RESISTANCE_TEST",
        "F6_STATOR_GROUND_TEST",
        "F7_REGULATOR_BLEED_BACK_TEST",
    ]
    by_id = {c["fact_id"]: c for c in verified}
    step = 1

    for fid in priority_order:
        c = by_id.get(fid)
        if not c:
            continue  # didn't clear QC yet — don't tell a stranded rider unverified info
        lines.append(f"### Step {step}: {_plain_english_title(fid)}")
        lines.append(_plain_english_body(c))
        lines.append("")
        step += 1

    return "\n".join(lines)


def _plain_english_title(fact_id: str) -> str:
    titles = {
        "F8_BATTERY_FIRST_RULE": "Check the battery first",
        "F9_STATIC_VOLTAGE_SPEC": "Test the battery at rest",
        "F1_RUNNING_VOLTAGE": "Test the battery while the engine runs",
        "F2_LOW_VOLTAGE_STATOR": "Low reading? It's probably the stator",
        "F3_HIGH_VOLTAGE_REGULATOR": "High reading? It's probably the regulator",
        "F10_GROUND_MIMICS_FAILURE": "Check your grounds before buying parts",
        "F4_STATOR_AC_OUTPUT_TEST": "Test the stator directly",
        "F5_STATOR_RESISTANCE_TEST": "Test the stator with the engine off",
        "F6_STATOR_GROUND_TEST": "Make sure the stator isn't shorted",
        "F7_REGULATOR_BLEED_BACK_TEST": "Test the regulator directly",
    }
    return titles.get(fact_id, fact_id)


def _plain_english_body(c: Dict[str, Any]) -> str:
    # Reuses the verified statement but keeps it short; the statement text
    # itself was already written in plain language during data entry.
    return c["statement"]
