"""
teacher.py — "The Teacher" / output-formatting layer of the Hourglass.

Takes only VERIFIED claims (never anything still pending QC) and renders two
real, distinct output tiers as specified in the original brief:
  - PRO tier: exact specs, ohm/voltage ranges, procedure steps, citations.
  - DIY / Roadside tier: plain-English, numbered, no-jargon steps for
    someone stressed on the side of the road with a multimeter and a phone.

Both tiers are generated from the *same* verified data — this is the
"expand and teach" step: once data clears the neck of the Hourglass, it is
formatted outward for every audience without re-deriving the facts.

GENERALIZATION NOTE (added when domain #2 was built):
format_diy_report() used to have a hardcoded step order and title map that
only worked for the charging-system domain's fact IDs. That meant every new
domain silently produced an empty/broken DIY report. It is now data-driven:
each claims_<domain>.json file may optionally supply "diy_order" (a list of
fact_ids in roadside-sensible order) and "diy_titles" (a fact_id -> plain
English title map). If a domain omits either, sensible generic fallbacks are
used so a brand-new domain always renders a usable DIY report out of the box.
"""

from typing import List, Dict, Any, Optional


def _fmt_citations(citations: List[str]) -> str:
    return "; ".join(citations)


def format_pro_report(domain: str, verified: List[Dict[str, Any]]) -> str:
    lines = [f"# {domain} — Professional Diagnostic Reference", ""]
    lines.append(
        "Generated by the RideWire Hourglass pipeline. Every entry below cleared "
        "Devil's QC (independent-source corroboration). Confidence reflects the "
        "number of independent domains that corroborate the claim, not just link count."
    )
    lines.append("")

    for c in sorted(verified, key=lambda x: x["fact_id"]):
        lines.append(f"## {c['fact_id']} ({c['category']}) — Confidence: {c['confidence']}")
        lines.append(c["statement"])
        if c.get("numeric_range"):
            lines.append(f"- Spec: `{c['numeric_range']}`")
        lines.append(f"- Corroborated by {c['independent_domain_count']} independent sources.")
        lines.append(f"- Citations: {_fmt_citations(c['citations'])}")
        lines.append("")

    return "\n".join(lines)


def format_diy_report(
    domain: str,
    verified: List[Dict[str, Any]],
    diy_order: Optional[List[str]] = None,
    diy_titles: Optional[Dict[str, str]] = None,
) -> str:
    lines = [f"# {domain} — Roadside / DIY Quick Guide", ""]
    lines.append(
        "If you're stuck on the side of the road: read this top to bottom, in order. "
        "You'll need a basic multimeter."
    )
    lines.append("")

    diy_order = diy_order or []
    diy_titles = diy_titles or {}
    by_id = {c["fact_id"]: c for c in verified}

    # Start with the domain's specified order (if any), then append any
    # verified claim not explicitly ordered — sorted by fact_id — so a claim
    # is never silently dropped just because a domain file forgot to list it.
    ordered_ids = [fid for fid in diy_order if fid in by_id]
    remaining_ids = sorted(fid for fid in by_id if fid not in ordered_ids)
    final_order = ordered_ids + remaining_ids

    step = 1
    for fid in final_order:
        c = by_id[fid]
        title = diy_titles.get(fid) or _fallback_title(c)
        lines.append(f"### Step {step}: {title}")
        lines.append(_plain_english_body(c))
        lines.append("")
        step += 1

    return "\n".join(lines)


def _fallback_title(c: Dict[str, Any]) -> str:
    """Generic title for any fact_id a domain didn't explicitly title.

    Falls back to the claim's category in plain words plus a short slice of
    its own fact_id, since the statement itself is usually a full sentence
    and too long for a heading.
    """
    category_label = c.get("category", "note").replace("_", " ").capitalize()
    return f"{category_label}: {c['fact_id'].split('_', 1)[-1].replace('_', ' ').title()}"


def _plain_english_body(c: Dict[str, Any]) -> str:
    # Reuses the verified statement but keeps it short; the statement text
    # itself was already written in plain language during data entry.
    return c["statement"]
